### ISSUE TITLE
AE

### ISSUE THREAD

**Issue by sfergusond** [rrodriguezbarron/UML-Project#15]
I messed with an autoencoder this morning. The results look good! You can find my code in the working branch. I didn't extensively test using different arrangements of the layers/nodes. The graphs below are from a (8, 8, 2) arrangement. 

![ae ideology](https://user-images.githubusercontent.com/4807415/117579408-55823600-b0b8-11eb-96b7-45b9815b9334.png)
![ae importance list](https://user-images.githubusercontent.com/4807415/117579409-561acc80-b0b8-11eb-97a2-8d26419f94f6.png)
![ae party](https://user-images.githubusercontent.com/4807415/117579410-561acc80-b0b8-11eb-97ff-3171a356c8a2.png)
![ae radio all things considered](https://user-images.githubusercontent.com/4807415/117579411-561acc80-b0b8-11eb-98ae-c8c7e3f933b0.png)
![ae radio fresh air](https://user-images.githubusercontent.com/4807415/117579413-561acc80-b0b8-11eb-9af1-fe01c1b34ac8.png)
![ae radio marketplace](https://user-images.githubusercontent.com/4807415/117579414-561acc80-b0b8-11eb-8b02-1da7df89399c.png)
![ae radio the glenn beck program](https://user-images.githubusercontent.com/4807415/117579415-56b36300-b0b8-11eb-8c1e-4fecdab8f9ac.png)
![ae radio the mark levin show](https://user-images.githubusercontent.com/4807415/117579416-56b36300-b0b8-11eb-94f8-10252c7d13cc.png)
![ae radio the mike gallagher show](https://user-images.githubusercontent.com/4807415/117579417-56b36300-b0b8-11eb-96ab-e9fc91383504.png)

**Comment by rrodriguezbarron** [comment]
GREAT, I'm still struggling to get my H2o working so I don't think I'll be running AEs anytime soon. If I may ask, why 8x2x2? Also, I think it's very interesting that we got such a CLEAR differentiation across party lines on the factors (even on the third layer). Finally, how does the first layer look when you color by party?
