### ISSUE TITLE
Abstract Summaries

### ISSUE THREAD

**Issue by rrodriguezbarron** [rrodriguezbarron/UML-Project#24]
Please type here the couple of lines you want in the abstract for your sections.

**Comment by sfergusond** [comment]
Using LLE, we find significant separation in the viewership of political media between the self-reported political ideologies of respondents. Further investigation using LLE showed little political separation in the viewership of strictly entertainment-based TV shows, though shows relying on specific political or cultural themes do tend to create some separation.

**Comment by rheuer83** [comment]
Additional analyses using autoencoders supported the results obtained with LLE. We deployed association rule mining to guide our visual inspection of the dataspace. Combinations of entertainment and political media formats suggested by association rules yielded interesting subsets with respect to ideological leaning.

**Comment by rrodriguezbarron** [comment]
Added all abstract summaries.
