### ISSUE TITLE
Variable Codes for Media Consumption (V161364 - V161443)

### ISSUE THREAD

**Issue by rheuer83** [rrodriguezbarron/UML-Project#7]
Sample item: 

"Which of the following television programs do you watch regularly? Please check any that you watch at least once a month. (Mark all that apply)"

0: Not Selected
1: Selected
-1: Inapplicable
-5: Breakoff, suff partial IW
-9: Refused

**Comment by rrodriguezbarron** [comment]
I suggest we make 0, 1, and everything else should be NA.
