### ISSUE TITLE
LLE

### ISSUE THREAD

**Issue by rrodriguezbarron** [rrodriguezbarron/UML-Project#9]
Made this new issue only for LLE stuff on the feeling thermometers. We still need to clean up the data of negative and >100 numbers.

**Comment by rrodriguezbarron** [comment]
I ran the FTs in LLE for 20 mins. as a test. As @sfergusond suggested, will change it to other once the new code from #11

**Comment by rrodriguezbarron** [comment]
@sfergusond just updated the LLE.Rmd. I think we should run all FTs now that they're clean. Will take a lunch break and will be back after a meeting (approx 17:00).

**Comment by sfergusond** [comment]
![lle_k96](https://user-images.githubusercontent.com/4807415/116473926-7091b200-a83d-11eb-9bc6-511ae8d31e62.png)
![lle_k5](https://user-images.githubusercontent.com/4807415/116473938-75eefc80-a83d-11eb-8da4-f13e04ab1b7b.png)

**Comment by rrodriguezbarron** [comment]
These look great.

Party ID and Ideology being similar is not surprising. The interesting part there are the moderates and leaners. We should intersect that by party later - maybe as a third dimension since that’s as much as we can do? Or maybe 7 two-dimensional LLEs (one for each leaning)?

 I’ll also do more work later to see if I can find some theoretical explanation for the dimensions and the clusters.

**Comment by sfergusond** [comment]
LLE results by Party/Ideology. I've recoded party2 and ideology2 to include all (lean/slightly through strong/extreme) values.

![lle_ideology2](https://user-images.githubusercontent.com/4807415/117551829-c1f42b00-b00d-11eb-9e90-83332faea25a.png)
![lle_part2](https://user-images.githubusercontent.com/4807415/117551830-c3255800-b00d-11eb-91b8-d29499830c12.png)
![lle_party](https://user-images.githubusercontent.com/4807415/117551831-c3255800-b00d-11eb-9c24-d2727dd8d73f.png)

**Comment by sfergusond** [comment]
Apologies for the photo dump - but here are the (interesting) radio LLE results.

![lle radio all things considered](https://user-images.githubusercontent.com/4807415/117551867-ec45e880-b00d-11eb-8c9e-5869c2ad5bfd.png)
![lle radio fresh air](https://user-images.githubusercontent.com/4807415/117551868-ec45e880-b00d-11eb-9bf2-856f58c3f1d5.png)
![lle radio no radio](https://user-images.githubusercontent.com/4807415/117551869-ecde7f00-b00d-11eb-8711-bfad98dfda9f.png)
![lle radio the glenn beck program](https://user-images.githubusercontent.com/4807415/117551871-ecde7f00-b00d-11eb-9d45-f38683cc46d8.png)
![lle radio the mark levin show](https://user-images.githubusercontent.com/4807415/117551872-ecde7f00-b00d-11eb-9c49-a81c71c013e0.png)
![lle radio the mike gallagher show](https://user-images.githubusercontent.com/4807415/117551873-ecde7f00-b00d-11eb-9c3d-53cdcf41f13a.png)
![lle radio the thom hartmann program](https://user-images.githubusercontent.com/4807415/117551874-ecde7f00-b00d-11eb-9e97-484f69e5df3a.png)

**Comment by rrodriguezbarron** [comment]
Sorry, I think I replied in the chat about these, but they look great. I just want to ask: how many NAs did you have for these shows? I know we are using NA == mean (Issue #13) but not for these ones. In a way, I believe it is very telling that some people don't even know about these programs. Perhaps we could code them as 0 for one test to see where they stand? Or maybe 2 and color them like so to see the difference between the YES, NO, and the "I didn't know that program was a thing"?
